[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_gameplay = "58aRQ8LWqsrnxgWY77b6DZmT4pxWF17cazq9eG1eU7br"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
